services:
  app:
    build: .  # Build the Docker image using the Dockerfile in the current directory
    container_name: telegram-notifier-dev  # Name the container for easy reference
    ports:
      - "8000:80"  # Map port 8000 on the host to port 80 in the container
    volumes:
      - .:/app  # Mount the current directory to /app in the container for live code updates
